version: '3'

services:
  server:
    build: server
    container_name: red_server
    ports:
      - "80:80"
    volumes:
      - ./magento2/:/var/www/html/magento2/
    networks:
      - network-back

  db:
    image: mariadb
    container_name: red_mariadb
    volumes:
      - ./dumps:/dumps
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - network-back

  mailhog:
    image: mailhog/mailhog:latest
    container_name: red_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - network-back

  redis:
    image: redis
    container_name: red_redis
    ports:
      - "6379:6379"
    networks:
      - network-back

networks:
  network-back:
    driver: bridge