version: '2'

services:
  apache2:
    build: apache2
    container_name: apache2
    ports:
      - "80:80"
    volumes:
      - ./magento2/:/var/www/html/magento2/
    networks:
      - network-back

  php:
    build: php
    container_name: php
    volumes:
      - ./magento2/:/var/www/html/magento2/
    networks:
      - network-back

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - network-back

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
        - network-back


networks:
    network-back:
        driver: bridge