<?php
/**
 * Redstage\NewsletterPopup\Block\Popup $block
 */
?>
<div data-mage-init='{"newsletter_popup": {}}'>
</div>

<div id="popup-modal" >
    <h2><?php echo __("Get the best promotions!"); ?></h2>
    <p id="response_ajax"></p>
    <form action="/newsletterpopup/newslwetter/save">
        <label for="email"><?php echo __('E-mail'); ?></label>
        <input id="email" name="email" type="text">
        <label for="name"><?php echo __('Name'); ?></label>
        <input id="name" name="name" type="text">
        <label for="name"><?php echo __('Phone'); ?></label>
        <input id="phone" name="phone" type="text">
        <?php echo $block->getBlockHtml('formkey'); ?>
    </form>
</div>