<?php
/**
 * Redstage\NewsletterPopup\Block\Popup $block
 */
?>
<div data-mage-init='{"newsletter_popup": {}}'>
</div>

<div id="popup-modal" >
    <h2>Get the best promotions!</h2>
    <form action="/newsletterpopup/newsletter/save">
        <label for="email"><?php echo __('E-mail'); ?></label>
        <input name="email" type="text">
        <label for="name"><?php echo __('Name'); ?></label>
        <input name="name" type="text">
        <label for="name"><?php echo __('Phone'); ?></label>
        <input name="phone" type="text">
        <?php echo $block->getBlockHtml('formkey'); ?>
    </form>
</div>